### PR TITLE
Issue 7

### LINKED ISSUE #7: cleanup webpack/connect config and scripts
With the webpack dev server, grunt connect should not be needed. We can clean this up and make sure hot reloading is working.

Note: webpack dev server hot reloading will not work inside the dockerized version on a mac. Do we need to support this? Polling should work.

### PR DESCRIPTION
**Pull request by emirose**
Fixes #7 

This PR includes:
- removing grunt-connect
- loading images, fonts, and html through webpack
- npm scripts for running webpack build and webpack dev server
- removing grunt tasks that are duplicates of what wepack is doing (let me know if I went overkill here :-))

There is more cleanup that could be done, but I wanted to make sure I'm on the right track here.

### CODE REVIEW

**Comment by adamhope** [comment]
It looks pretty good overall and I really appreciate you cleaning up the huge unfinished refactor!

The only thing I'm unsure about is the value of loading images via webpack/referencing them from the JS files. Is there a reason we can't server them from a single images directory? Is it so we can get rid of watch and connect?

**Comment by emirose** [comment]
Yep, good catch about the image file. I meant to clean that up. Ideally, I think that webpack should load the images based on the html/handlebar templates (unless we feel like that's too much magic?). The handlebar loader has some weird behavior around this, but I'll take another look. I think the other option is to keep the grunt copy task just for the images. Let me know if you have other ideas.

Thanks for the fast feedback!

**Comment by adamhope** [comment]
Sounds like a plan, I think loading static assets via the HTML templates would be much simpler and more obvious behavior.

**Comment by emirose** [comment]
The handlebar loader loads the images now. Let me know if you want me to make any more changes.

What are your thoughts on the FIXME in the webpack.config? Are you thinking jQuery, _, and Backbone should be imported explicitly where they are used?

**Pull request merged**
