### PR TITLE
WIP: Vanillajs

### PR DESCRIPTION
**Pull request by raytung**
Introduction:
- No external frameworks / libraries. Simply vanilla ES6.
- `jest` for testing (jest provides `jsdom` so we can remove `phantomjs`!)
- Once we remove the `watch_framework` dependency we can remove `jquery`, `Backbone`, and `underscore`.

Working:
- [x] Navigation
- [x] Button events

Not working:
- Notification

`App.js` is where everything hooks together. I'm not happy about how the `navigate` function is passed around, but we can figure that out later. (Perhaps Redux style)?

- Every "Component" must inherit from the `BaseComponent` class, which basically mandates a `template` function that returns a HTML string.
- Every "Page" must inherit from the `BasePage` class, which provides the `navigate` function, access to the `watchFace` element

@sinan-aumarah @sitajaf

### CODE REVIEW

**Comment by raytung** [comment]
btw this is a rough prototype, some tests are not passing. ¯\\_(ツ)_/¯

**Comment by watsonarw** [comment]
@raytung I've had a look, really good stuff. What else do we need to do to get this to a point where everything is working and we can merge this back?

**Comment by raytung** [comment]
@watsonarw Hey thanks! At the moment there are at least 3 things we need to do before we can merge this back to trunk:

- [] Feature: Notification
- [] Fix up failing tests
- [] Remove unused code

Post merge:
- [] Update wiki / tutorials

**Comment by honsq90** [comment]
- We've updated the test runner to jest
- Created a very simple notification system that doesn't use Backbone's EventHub
- Adding notifications is just updating the array in `client/src/js/notifications.js`
- OK & Cancel just dismiss the notification
- Changing the page dismisses the notification

**Pull request merged**
